import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useStore } from '../store';
import Input from '../components/ui/Input';
import Button from '../components/ui/Button';
import { Shield, Mail, Lock, User } from 'lucide-react';
import { accxApi } from '../lib/accxApi';

export default function RegisterPage() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const setUser = useStore(s => s.setUser); const navigate = useNavigate();
  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password !== confirmPassword) return setError('Passwords do not match.'); if (password.length < 12) return setError('Password must contain at least 12 characters.'); setLoading(true); try { const { user } = await accxApi.register(name, email, password); setUser(user); navigate('/'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create account.'); } finally { setLoading(false); } };
  return <div className="min-h-screen flex"><div className="hidden lg:flex lg:w-1/2 gradient-brand relative overflow-hidden"><div className="absolute inset-0 opacity-10"><div className="absolute top-20 left-20 w-72 h-72 bg-white rounded-full blur-3xl" /><div className="absolute bottom-20 right-20 w-96 h-96 bg-white rounded-full blur-3xl" /></div><div className="relative z-10 flex flex-col justify-center px-16 text-white"><div className="w-14 h-14 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center mb-8"><Shield className="w-7 h-7" /></div><h1 className="text-4xl font-bold mb-4 tracking-tight">ACCX</h1><p className="text-xl text-white/80 mb-8 max-w-md">Create your cloud control plane. Managed credentials never become browser data.</p></div></div><div className="flex-1 flex items-center justify-center p-8 bg-bg-base"><div className="w-full max-w-md animate-fade-in"><div className="lg:hidden flex items-center gap-3 mb-8"><div className="w-10 h-10 rounded-xl gradient-brand flex items-center justify-center"><Shield className="w-5 h-5 text-white" /></div><span className="text-xl font-bold tracking-tight">ACCX</span></div><h2 className="text-2xl font-bold text-text-primary mb-1">Create your account</h2><p className="text-text-muted mb-8">Provision your cloud workspace in seconds</p><form onSubmit={handleSubmit} className="space-y-4"><Input label="Full Name" type="text" placeholder="John Doe" value={name} onChange={e => setName(e.target.value)} icon={<User className="w-4 h-4" />} required /><Input label="Email" type="email" placeholder="john@example.com" value={email} onChange={e => setEmail(e.target.value)} icon={<Mail className="w-4 h-4" />} required /><Input label="Password" type="password" placeholder="At least 12 characters" value={password} onChange={e => setPassword(e.target.value)} icon={<Lock className="w-4 h-4" />} required /><Input label="Confirm Password" type="password" placeholder="Repeat your password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} icon={<Lock className="w-4 h-4" />} required />{error && <div className="p-3 rounded-xl bg-danger-subtle border border-danger-theme/20 text-sm text-danger-theme animate-scale-in">{error}</div>}<Button type="submit" loading={loading} className="w-full" size="lg">Create Account</Button></form><p className="text-center text-sm text-text-muted mt-6">Already have an account? <Link to="/login" className="text-accent hover:text-accent-hover font-medium">Sign in</Link></p></div></div></div>;
}
